application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  # the single sender email I authorize on Postmark
  sender_email: "something@gmail.com"